-- CREATE TABLE PLANT ( id SERIAL,
--                      PICTURE TEXT, BOTANICAL_NAME TEXT, COMMON_NAME TEXT, TRANSLATION VARCHAR(255), PLANT_OVERVIEW TEXT,
--                      NATIVE_AREA VARCHAR(255), PLANT_TYPE VARCHAR(255), MATURE_SIZE INTEGER,CARE_DIFFICULTY INTEGER, CARE_DESCRIPTION TEXT,
--                      WATER INTEGER, WATER_EXTENDED TEXT, SUN INTEGER, SUN_EXTENDED TEXT, TEMPERATURE TEXT,HUMIDITY TEXT,
--                      FERTILIZER INTEGER, BLOOM_TIME TEXT, REPOTTING INTEGER, REPOTTING_EXTENDED TEXT, TOXICITY BOOLEAN, SOIL_TYPE TEXT,
--                      SOIL_PH TEXT,PROPAGATING TEXT, PESTS_AND_DISEASES TEXT, PRUNING TEXT, AIR_PURIFYING BOOLEAN, FERTILIZER_EXTENDED TEXT
-- );

-- COPY PLANT(PICTURE, BOTANICAL_NAME, COMMON_NAME, TRANSLATION, PLANT_OVERVIEW, NATIVE_AREA,
--            PLANT_TYPE, MATURE_SIZE, CARE_DIFFICULTY, CARE_DESCRIPTION, WATER,
--            WATER_EXTENDED, SUN, SUN_EXTENDED, TEMPERATURE, HUMIDITY, FERTILIZER,
--            BLOOM_TIME, REPOTTING, REPOTTING_EXTENDED,
--            TOXICITY,  SOIL_TYPE, SOIL_PH, PROPAGATING, PESTS_AND_DISEASES, PRUNING, AIR_PURIFYING, FERTILIZER_EXTENDED)
--     FROM 'C:/Users/kiza/Desktop/sprout.csv'
--     DELIMITER ','
--     CSV HEADER;

<<<<<<< HEAD
INSERT INTO PLANT (
    BOTANICAL_NAME, COMMON_NAME, TRANSLATION, PLANT_OVERVIEW, NATIVE_AREA,
    PLANT_TYPE, MATURE_SIZE, CARE_DIFFICULTY, CARE_DESCRIPTION, WATER,
    WATER_EXTENDED, SUN, SUN_EXTENDED, TEMPERATURE, HUMIDITY, FERTILIZER,
    BLOOM_TIME, REPOTTING, REPOTTING_EXTENDED,
    TOXICITY,  SOIL_TYPE, SOIL_PH, PROPAGATING, PESTS_AND_DISEASES, PRUNING, AIR_PURIFYING, FERTILIZER_EXTENDED
)
SELECT
    BOTANICAL_NAME, COMMON_NAME, TRANSLATION, PLANT_OVERVIEW, NATIVE_AREA,
    PLANT_TYPE, MATURE_SIZE, CARE_DIFFICULTY, CARE_DESCRIPTION, WATER,
    WATER_EXTENDED, SUN, SUN_EXTENDED, TEMPERATURE, HUMIDITY, FERTILIZER,
    BLOOM_TIME, REPOTTING, REPOTTING_EXTENDED,
    TOXICITY,  SOIL_TYPE, SOIL_PH, PROPAGATING, PESTS_AND_DISEASES, PRUNING, AIR_PURIFYING, FERTILIZER_EXTENDED
FROM CSVREAD('classpath:plants.csv');
=======
>>>>>>> 934dacd1572a60e7ddd848d0a5a61e1ca8377c8d
