
INSERT INTO PLANT (
    ID, BOTANICAL_NAME, COMMON_NAME, TRANSLATION, PLANT_OVERVIEW, NATIVE_AREA,
    PLANT_TYPE, MATURE_SIZE, CARE_DIFFICULTY, CARE_DESCRIPTION, WATER,
    WATER_EXTENDED, SUN, SUN_EXTENDED, TEMPERATURE, HUMIDITY, FERTILIZER,
    BLOOM_TIME, REPOTTING, REPOTTING_EXTENDED,
    TOXICITY,  SOIL_TYPE, SOIL_PH, PROPAGATING, PESTS_AND_DISEASES, PRUNING, AIR_PURIFYING, FERTILIZER_EXTENDED
)
SELECT
    ID, BOTANICAL_NAME, COMMON_NAME, TRANSLATION, PLANT_OVERVIEW, NATIVE_AREA,
    PLANT_TYPE, MATURE_SIZE, CARE_DIFFICULTY, CARE_DESCRIPTION, WATER,
    WATER_EXTENDED, SUN, SUN_EXTENDED, TEMPERATURE, HUMIDITY, FERTILIZER,
    BLOOM_TIME, REPOTTING, REPOTTING_EXTENDED,
    TOXICITY,  SOIL_TYPE, SOIL_PH, PROPAGATING, PESTS_AND_DISEASES, PRUNING, AIR_PURIFYING, FERTILIZER_EXTENDED
FROM CSVREAD('classpath:plants.csv');